import { StyleSheet } from 'react-native';
import { COLORS } from '../../Common/Colors';
import { FONTS_FAMILY } from '../../Common/FontsFamily';
import { normalize } from '../../Globals/normalize';
import {
  ScreenHeight,
  ScreenWidth,
  font_11,
  font_12,
  font_15,
  font_16,
} from '../../Globals/fonts';

export const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: COLORS.secondaryLight,
    flex: 1,
  },
  backIconStyle: {
    height: normalize(25),
    width: normalize(25),
  },
  imgBackgroundStyle: {
    height: ScreenHeight * 0.3,
    width: ScreenWidth,
    borderBottomRightRadius: normalize(12),
    borderBottomLeftRadius: normalize(12),
  },
  iconContainer: {
    backgroundColor: COLORS.white,
    height: normalize(40),
    width: normalize(40),
    borderRadius: normalize(20),
    alignItems: 'center',
    justifyContent: 'center',
    shadowRadius: 3,
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.2,
    shadowColor: COLORS.black,
    elevation: 4,
    marginLeft: normalize(10),
    marginTop: normalize(30),
    position: 'absolute',
  },
  headerContainer: {
    borderRadius: normalize(20),
  },
  nameContianer: {
    marginTop: normalize(10),
    marginHorizontal: normalize(10),
    flexDirection: 'row',
  },
  ngoLogo: {
    borderRadius: normalize(35),
    height: normalize(70),
    width: normalize(70),
  },
  txtName: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_16,
    color: COLORS.blackText,
    textAlign: 'left',
    fontWeight: '500',
  },
  txtDate: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_11,
    color: COLORS.lightGray,
    textAlign: 'left',
    fontWeight: '500',
    marginTop: normalize(6),
  },
  txtContainerView: {
    alignItems: 'flex-start',
    marginLeft: normalize(10),
    alignSelf: 'center',
  },
  txtEventNameStyle: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_16,
    color: COLORS.blackText,
    textAlign: 'left',
    fontWeight: '500',
    marginTop: normalize(10),
    marginLeft: normalize(15),
  },
  txtEventDesStyle: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_12,
    color: COLORS.blackText,
    textAlign: 'left',
    fontWeight: '500',
    marginTop: normalize(7),
    marginLeft: normalize(15),
    marginRight: normalize(30),
  },
  grayViewStyle: {
    backgroundColor: COLORS.graylighter,
    width: '100%',
    height: normalize(40),
    marginTop: normalize(15),
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: normalize(15),
  },
  inactiveTxtStyle: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_16,
    color: COLORS.grayFont,
    textAlign: 'left',
    fontWeight: '600',
    textAlign: 'center',
    width: normalize(150),
    height: normalize(40),
    alignSelf: 'center',
    lineHeight: normalize(40),
  },
  activeTxtStyle: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_16,
    color: COLORS.secondary,
    textAlign: 'left',
    fontWeight: '600',
    textAlign: 'center',
    width: normalize(150),
    height: normalize(40),
    alignSelf: 'center',
    lineHeight: normalize(40),
    textAlignVertical: 'center',
  },
  underlineTxtStyle: {
    height: 4,
    width: normalize(150),
    borderWidth: 0.5,
    borderColor: COLORS.graylighter,
    borderRadius: normalize(2),
    marginTop: -5,
    backgroundColor: COLORS.graylighter,
  },
  iconContainerView: {
    backgroundColor: COLORS.white,
    borderRadius: normalize(25),
    height: normalize(50),
    width: normalize(50),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: normalize(30),
    alignSelf: 'center',
  },
  callIconStyle: {
    height: normalize(35),
    width: normalize(35),
  },
  txtNumberStyle: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_16,
    color: COLORS.blackText,
    textAlign: 'left',
    fontWeight: '500',
    textAlign: 'center',
    marginTop: normalize(10),
  },
  containerBtns: {
    flexDirection: 'row',
    marginHorizontal: normalize(10),
    marginTop: normalize(20)
  },
  btnGrabStyle: {
    backgroundColor: COLORS.secondary,
    flex: 1,
    marginHorizontal: normalize(5),
    padding: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(12),
    borderWidth: 0.5,
    borderColor: COLORS.secondary,
    height: normalize(40)
  },
  btnShareStyle: {
    backgroundColor: COLORS.secondaryLight,
    flex: 1,
    marginHorizontal: normalize(5),
    padding: normalize(10),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: normalize(12),
    borderWidth: 0.5,
    borderColor: COLORS.secondary,
    height: normalize(40)
  },
  txtGrabStyle: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_16,
    color: COLORS.white,
  },
  txtShareStyle: {
    fontFamily: FONTS_FAMILY.poppins_medium,
    fontSize: font_16,
    color: COLORS.secondary,
  }
});
